apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: global-cq
spec:
  namespaceSelector: {}
  admissionChecks:
    - multikueue-check
  resourceGroups:
    - coveredResources: ["cpu", "memory", "nvidia.com/gpu", "ephemeral-storage"]
      flavors:
        - name: standard
          resources:
            - name: "cpu"
              nominalQuota: 20
            - name: "memory"
              nominalQuota: 64Gi
            - name: "nvidia.com/gpu"
              nominalQuota: 0
            - name: "ephemeral-storage"
              nominalQuota: 100Gi
        - name: gpu-rtx6000
          resources:
            - name: "cpu"
              nominalQuota: 20
            - name: "memory"
              nominalQuota: 64Gi
            - name: "nvidia.com/gpu"
              nominalQuota: 100
            - name: "ephemeral-storage"
              nominalQuota: 100Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: demo-queue
  namespace: demo-jobs
spec:
  clusterQueue: global-cq
