apiVersion: batch/v1
kind: Job
metadata:
  generateName: obtainability-demo-
  namespace: demo-jobs
  labels:
    kueue.x-k8s.io/queue-name: demo-queue
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: dummy-job
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c", "echo 'Running job in region:' && curl -s http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google' && echo && sleep 30"]
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Never
